version: '3.8'

services:
  react-ts-project:
    container_name: react-ts-project
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: builder
    volumes:
      - ../:/workdir
    stdin_open: true
    tty: true
    entrypoint: /bin/sh